version: "3.9"

services:
  php-apache:
    ports:
      - "80:80"
    build: 'Build/Php-Apache'
    volumes:
      - ./App:/var/www/html
  mysql:
    ports:
      - "3306:3306"
    build: './Build/Mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "super-secret-password"
      MYSQL_DATABASE: "my-wonderful-website"
    volumes:
      - dbData:/var/lib/mysql

volumes:
  app:
  dbData: