name: Deploy to VPS

on:
  push:
    branches:
      - main

env:
  VPS_USER: ${{ secrets.VPS_USER }}
  VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
  VPS_HOST: ${{ secrets.VPS_HOST }}
  APP_PATH: ${{ variables.APP_PATH }}
  DOCKER_COMPOSE_FILE: docker-compose.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: vps

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y openssh-client sshpass

      - name: copy files to VPS
        env:
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          APP_PATH: ${{ variable.APP_PATH }}
        run: sshpass -p $VPS_PASSWORD scp -o StrictHostKeyChecking=no -r .$VPS_USER@VPS_HOST:$APP_PATH

      - name: Deploy using docker-compose
        env:
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
          DOCKER_COMPOSE_FILE: docker-compose.yml
        run: | 
          sshpass -p $VPS_PASSWORD ssh -o StrictHostKeyChecking=no » ./ $VPS_USER@VPS_HOST << ‘EOF’
  	      cd $APP_PATH
  	      docker-compose down
          docker-compose up-d
          EOF