name: Deploy to VPS

on:
  push:
    branches:
      - main

env:
  VPS_USER: ${{ secrets.VPS_USER }}
  VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
  VPS_HOST: ${{ secrets.VPS_HOST }}
  VPS_PORT: ${{ secrets.VPS_PORT }}
  APP_PATH: zoo-arcadia
  DOCKER_COMPOSE_FILE: docker-compose.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: vps

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y openssh-client sshpass

      - name: copy files to VPS
        run: sshpass -p $VPS_PASSWORD scp -P $VPS_PORT -o StrictHostKeyChecking=no -r ./* $VPS_USER@$VPS_HOST:$APP_PATH

      - name: Deploy using docker-compose
        run: |
          sshpass -p $VPS_PASSWORD ssh -p $VPS_PORT -o StrictHostKeyChecking=no -T $VPS_USER@$VPS_HOST << 'EOF'
            cd zoo-arcadia
            pwd
            docker compose up -d
          EOF